Bots Funcionando Correctamente
Igual no esta de más hacer varias pruebas, pero ya se puede jugar en solitario

los bots en cada escena pueden tener diferente personalidad, revisar como funciona

a mi me sale un error que es:
MissingReferenceException: The object of type 'UnityEngine.RectTransform' has been destroyed but you are still trying to access it.
Your script should either check if it is null or you should not destroy the object

Creo que es porque se termina el juego y se superpone mientras esta terminando la animación de la carta al descartarla, hay que revisar si solo me pasa a mi o a ustedes tambien